services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: AKASH
      POSTGRES_PASSWORD: AKASH
      POSTGRES_DB: nexli_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: